#!/bin/sh

#DIR_PATH=$(dirname $(readlink -f "${BASH_SOURCE:-$0}"))

start-stop-daemon --start --exec /usr/bin/aesdsocket -- -d 
if [ $? -eq 1 ]; then
  start-stop-daemon --stop --exec /usr/bin/aesdsocket 
fi
